<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AyushRaj" failures="1" tests="6" name="Default test" time="1.079" errors="0" timestamp="2021-08-28T22:43:09 IST">
  <testcase classname="com.org.test3.AttributeDependOnMethodeTests" name="FetchUserDetails" time="1.017">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.org.test3.AttributeDependOnMethodeTests.FetchUserDetails() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.org.test3.AttributeDependOnMethodeTests.FetchUserDetails() didn't finish within the time-out 1000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- FetchUserDetails -->
  <testcase classname="com.org.test3.AttributeDependOnMethodeTests" name="OpenBrowser" time="0.001"/>
  <testcase classname="com.org.test3.AttributeDependOnMethodeTests" name="LoginPage" time="0.001"/>
  <testcase classname="com.org.test3.AttributeDependOnMethodeTests" name="AddtoCart" time="0.001"/>
  <testcase classname="com.org.test3.AttributeDependOnMethodeTests" name="Checkout" time="0.001"/>
  <testcase classname="com.org.test3.AttributeDependOnMethodeTests" name="CleanupDataBase" time="0.001"/>
</testsuite> <!-- Default test -->
